### ISSUE TITLE
RuntimeError should be catchable by error tests

### ISSUE THREAD

**Issue by saper** [sass/sass-spec#501]
(Strange behavior seen https://github.com/sass/sass-spec/pull/463)

As a consequence, `--nuke` does not generate error files after #494 

````
  7) Error:
SassSpec::Test#test__expanded_spec/libsass-todo-issues/issue_1418/static:
RuntimeError: Command `sass` did not complete:


    /home/saper/sw/libsass/sass-spec/lib/sass_spec/test.rb:17:in `run_spec_test'
    /home/saper/sw/libsass/sass-spec/lib/sass_spec/test.rb:50:in `block (2 levels) in create_tests'
````

**Comment by saper** [comment]
Probably my mistake, closing.
